backend/Ictfabriek/urls.py
from django.urls import include, path
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin

from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)


urlpatterns = [
    path('', include('tickets.urls')),
    path('tickets/', include('tickets.urls')),
    path('api/v1/', include('api.urls')),
    path('api/auth/', include('rest_framework.urls', namespace='rest_framework')),
    path('api/auth/token/obtain/', TokenObtainPairView.as_view()),
    path('api/auth/token/refresh/', TokenRefreshView.as_view()), 
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

backend/api/urls.py
from django.urls import path, include
from . import views
from rest_framework import routers

router = routers.DefaultRouter()

router.register('klant', views.KlantView)
router.register('apparaat', views.ApparaatView)
router.register('ticket', views.TicketView)
router.register('opmerking', views.OpmerkingView)
router.register('user', views.UserView)

urlpatterns = [
    path('', include(router.urls)),
]

backend/tickets/urls.py
from django.urls import path

from . import views


app_name = 'tickets'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('login/', views.UserLoginView.as_view(), name='login'),
    path('overzicht/tickets/', views.OverzichtViewTicket.as_view(), name='overzicht_ticket'),
    path('overzicht/tickets_open/', views.OverzichtViewTicketOpen.as_view(), name='overzicht_ticket_open'),
    path('overzicht/klanten/', views.OverzichtViewKlant.as_view(), name='overzicht_klant'),
    path('overzicht/notificaties/', views.OverzichtViewNotificatie.as_view(), name="overzicht_notificatie"),
    path('factuur/<int:pk>/extra_artikel/', views.ArtikelCreateView.as_view(), name="extra_artikel"),
    path('ticket/<int:pk>/', views.DetailViewTicket.as_view(), name='detail'),
    path('klant/<int:pk>/', views.DetailViewKlant.as_view(), name="klant_detail"),
    path('nieuw_ticket/klant/', views.KlantCreateView.as_view(), name="nieuw_klant"),
    path('<int:pk>/edit_klant/', views.KlantUpdateView.as_view(), name="edit_klant"),
    path('<int:pk>/delete_klant/', views.KlantDeleteView.as_view(), name="delete_klant"),
    path('nieuw_ticket/<int:pk>/apparaat/', views.ApparaatCreateView.as_view(), name="nieuw_apparaat"),
    path('<int:pk>/edit_apparaat/', views.ApparaatUpdateView.as_view(), name="edit_apparaat"),
    path('<int:pk>/delete_apparaat/', views.ApparaatDeleteView.as_view(), name="delete_apparaat"),
    path('<int:ticket_id>/plaats_opmerking/', views.plaats_opmerking, name="plaats_opmerking"),
    path('<int:pk>/delete_opmerking/', views.OpmerkingDeleteView.as_view(), name="delete_opmerking"),
    path('nieuw_ticket/<int:pk>/ticket/', views.TicketKlantView.as_view(), name="klant_ticket"),
    path('<int:pk>/edit_ticket/', views.TicketUpdateView.as_view(), name="edit_ticket"),
    path('<int:pk>/delete_ticket/', views.TicketDeleteView.as_view(), name="delete_ticket"),
    path('<int:ticket_id>/ticket_afsluiten/', views.ticket_afsluiten, name="ticket_afsluiten"),
    path('<int:notificatie_id>/delete_notificatie/', views.delete_notificatie, name="delete_notificatie"),
    path('<int:opmerking_id>/plaats_antwoord/', views.plaats_antwoord, name="plaats_antwoord"),
    path('ajax/zoek_klant/', views.ajax_get_klant, name="zoek_klant"),
    path('ajax/apparaat', views.ajax_add_device, name="ajax_apparaat"),
    path('ajax/artikel_toevoegen/<int:factuur_id>/', views.ajax_artikel_toevoegen, name="ajax_artikel_toevoegen"),
    path('ajax/artikel_verwijderen/<int:artikel_id>/', views.ajax_artikel_verwijderen, name="ajax_artikel_verwijderen"),
    path('ajax/notificatie_gezien/<int:notificatie_id>/', views.ajax_notificatie_gezien, name="notificatie_gezien"),
    path('pdf/afhaalbewijs/ticket/<int:pk>/', views.GeneratePDF.as_view(), name="afhaalbewijs_pdf"),
    path('pdf/factuur/<int:pk>/', views.GenerateFactuur.as_view(), name="factuur_pdf"),
    path('<int:pk>/factuur/', views.FactuurCreateView.as_view(), name="maak_factuur"),
    path('loguit/', views.loguit_view, name='loguit')
]

backend/tickets/models.py
from django.db import models

from django.db import models
from django.urls import reverse

import datetime
from django.contrib.auth.models import User
from django.utils import timezone


class Klant(models.Model):
    class Meta:
        verbose_name_plural = "Klanten"

    klant_voornaam = models.CharField(max_length=50)
    klant_achternaam = models.CharField(max_length=50)
    klant_telefoonnummer = models.CharField(max_length=40)
    klant_straatnaam = models.CharField(max_length=100, blank=True, null=True)
    klant_huisnummer = models.IntegerField(blank=True, null=True)
    klant_postcode = models.CharField(max_length=7, blank=True, null=True)
    klant_woonplaats = models.CharField(max_length=70, blank=True, null=True)
    klant_emailadres = models.CharField(max_length=150, blank=True, null=True)
    klant_datum_aangepast = models.DateTimeField('Datum aangepast', null=True)
    klant_aangepast_door = models.ForeignKey(User, models.SET_NULL, blank=True, null=True)

    def get_apparaten(self):
        return self.apparaat_set.all()

    def heeft_apparaten(self):
        return len(self.apparaat_set.all()) > 0

    def get_tickets(self):
        return self.ticket_set.all()

    def heeft_tickets(self):
        return len(self.ticket_set.all()) > 0
    
    def get_aantal_tickets(self):
        return len(self.ticket_set.all())

    def get_absolute_url(self):
        return reverse('tickets:nieuw_apparaat', kwargs={'pk': self.pk})

    def __str__(self):
        return "{} {}".format(self.klant_voornaam, self.klant_achternaam)


class Apparaat(models.Model):
    class Meta:
        verbose_name_plural = "Apparaten"

    apparaat_merk = models.CharField(max_length=50)
    apparaat_type = models.CharField(max_length=100, blank=True, null=True)
    apparaat_serienummer = models.CharField(max_length=75, blank=True, null=True)
    apparaat_staat = models.CharField(max_length=250)
    apparaat_accessoires = models.CharField(max_length=250, blank=True, null=True)
    apparaat_klant = models.ForeignKey(Klant, on_delete=models.CASCADE, blank=True, null=True)

    def heeft_meer_tickets(self):
        return len(self.ticket_set.all()) > 1

    def get_tickets(self):
        return self.ticket_set.all()

    def heeft_accessoires(self):
        return self.apparaat_accessoires is not None

    def get_absolute_url(self):
        return reverse('tickets:klant_detail', kwargs={'pk': self.apparaat_klant.id})

    def __str__(self):
        return "{} {}".format(self.apparaat_merk, self.apparaat_type)


class Ticket(models.Model):
    PRIORITEIT_KEUZES = (
        ('laag', 'Laag'),
        ('normaal', 'Normaal'),
        ('hoog', 'Hoog')
    )
    STATUS_KEUZES = (
        ('In behandeling', 'In behandeling'),
        ('Afgesloten', 'Afgesloten'),
        ('Wachten op onderdelen', 'Wachten op onderdelen'),
        ('Wachten op reactie klant', 'Wachten op reactie klant'),
    )

    ticket_prioriteit = models.CharField(
        max_length=50,
        choices=PRIORITEIT_KEUZES,
        default='Normaal',
    )
    ticket_status = models.CharField(
        max_length=50,
        choices=STATUS_KEUZES,
        default="In behandeling",
    )
    ticket_onderwerp = models.CharField(max_length=100)
    ticket_body = models.CharField(max_length=1000)
    ticket_datum_aangemaakt = models.DateTimeField('datum aangemaakt')
    ticket_datum_aangepast = models.DateTimeField('datum aangepast', null=True)
    ticket_datum_verwijderd = models.DateTimeField('datum verwijderd', null=True)
    ticket_auteur = models.ForeignKey(User, models.SET_NULL, blank=True, null=True)
    ticket_auteur_bewerkt = models.ForeignKey(User, models.SET_NULL, blank=True, null=True, related_name='+')
    ticket_klant = models.ForeignKey(Klant, on_delete=models.CASCADE, blank=True, null=True)
    ticket_apparaat = models.ForeignKey(Apparaat, on_delete=models.SET_NULL, blank=True, null=True)

    def heeft_facturen(self):
        return len(self.factuur_set.all()) > 0

    def get_facturen(self):
        return self.factuur_set.all()

    def is_in_behandeling(self):
        return self.ticket_status == "In behandeling"

    def recent_aangemaakt(self):
        return self.ticket_datum_aangemaakt >= timezone.now() - datetime.timedelta(days=1)

    def recent_aangepast(self):
        return self.ticket_datum_aangepast >= timezone.now() - datetime.timedelta(days=1)

    def get_absolute_url(self):
        return reverse('tickets:detail', kwargs={'pk': self.pk})

    def get_apparaten(self):
        return self.ticket_apparaat.ticket_set.all()

    def __str__(self):
        return "Ticket nummer: {} '{}'".format(self.id, self.ticket_onderwerp)


class Opmerking(models.Model):
    class Meta:
        verbose_name_plural = "Opmerkingen"

    opmerking_type = models.CharField(max_length=25, default="informatie")
    opmerking_body = models.CharField(max_length=500, default="Geen")
    opmerking_datum_aangemaakt = models.DateTimeField('datum aangemaakt')
    opmerking_auteur = models.ForeignKey(User, models.SET_NULL, blank=True, null=True)
    opmerking_ontvanger = models.ForeignKey(User, models.SET_NULL, blank=True, null=True, related_name='+')
    opmerking_ticket = models.ForeignKey(Ticket, on_delete=models.CASCADE)

    def heeft_antwoorden(self):
        return len(self.antwoord_set.all()) > 0

    def get_antwoorden(self):
        return self.antwoord_set.all()

    def __str__(self):
        return self.opmerking_body + " - " + self.opmerking_type


class Antwoord(models.Model):
    class Meta:
        verbose_name_plural = "Antwoorden"

    antwoord_body = models.CharField(max_length=500, default="Geen")
    antwoord_datum_aangemaakt = models.DateTimeField('datum aangemaakt')
    antwoord_auteur = models.ForeignKey(User, models.SET_NULL, blank=True, null=True)
    antwoord_opmerking = models.ForeignKey(Opmerking, on_delete=models.CASCADE)

    def __str__(self):
        return self.antwoord_body


class Notificatie(models.Model):
    notificatie_body = models.CharField(max_length=250)
    notificatie_van = models.ForeignKey(User, models.SET_NULL, blank=True, null=True)
    notificatie_naar = models.ForeignKey(User, models.SET_NULL, blank=True, null=True, related_name='+')
    notificatie_datum_aangemaakt = models.DateTimeField('datum aangemaakt')
    notificatie_gezien = models.BooleanField(default=False)
    notificatie_opmerking = models.ForeignKey(Opmerking, on_delete=models.CASCADE, blank=True, null=True)
    notificatie_antwoord = models.ForeignKey(Antwoord, on_delete=models.CASCADE, null=True, blank=True)

    def heeft_gezien(self):
        return self.notificatie_gezien

    def __str__(self):
        return self.notificatie_body


class Artikel(models.Model):
    class Meta:
        verbose_name_plural = "Artikelen"

    artikel_naam = models.CharField(max_length=70)
    artikel_prijs = models.DecimalField(max_digits=50, decimal_places=2)
    artikel_omschrijving = models.CharField(max_length=250)

    def __str__(self):
        return self.artikel_naam


class Factuur(models.Model):
    class Meta:
        verbose_name_plural = "Facturen"

    factuur_ticket = models.ForeignKey(Ticket, models.SET_NULL, blank=True, null=True)
    factuur_klant = models.ForeignKey(Klant, on_delete=models.CASCADE)
    factuur_artikelen = models.ManyToManyField(Artikel)
    factuur_aangemaakt_door = models.ForeignKey(User, models.SET_NULL, blank=True, null=True)
    factuur_datum_aangemaakt = models.DateTimeField('datum_aangemaakt')
    factuur_werkzaamheden = models.CharField(max_length=10000, blank=True, default="Geen klacht geconstateerd")
    factuur_pdf_file = models.FileField(upload_to='facturen/', blank=True, null=True)

    def get_artikelen(self):
        return self.factuur_artikelen.all()

    def get_extra_artikelen(self):
        return self.nieuwartikel_set.all()

    def get_totaal(self):
        artikel_prijzen = [artikel.artikel_prijs for artikel in self.get_artikelen()]
        extra_artikel_prijzen = [artikel.nieuw_artikel_prijs for artikel in self.get_extra_artikelen()]
        return sum(artikel_prijzen) + sum(extra_artikel_prijzen)

    def __str__(self):
        return "Factuur nummer " + str(self.id)


class NieuwArtikel(models.Model):
    class Meta:
        verbose_name_plural = "Nieuwe artikelen"

    nieuw_artikel_naam = models.CharField(max_length=100)
    nieuw_artikel_prijs = models.DecimalField(max_digits=10, decimal_places=2)
    nieuw_artikel_omschrijving = models.CharField(max_length=200, blank=True, null=True)
    nieuw_artikel_toegev_door = models.ForeignKey(User, models.SET_NULL, blank=True, null=True)
    nieuw_artikel_datum_toegev = models.DateTimeField('datum aangemaakt')
    nieuw_artikel_factuur = models.ForeignKey(Factuur, on_delete=models.CASCADE)

    def __str__(self):
        return self.nieuw_artikel_naam

backend/tickets/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Ticket, Klant, Apparaat, Factuur, NieuwArtikel

class TicketForm(forms.ModelForm):
    class Meta:
        model = Ticket
        fields = ('ticket_onderwerp', 'ticket_body', 'ticket_prioriteit')
        widgets = {
            'ticket_body': forms.Textarea
        }


class KlantForm(forms.ModelForm):
    id = forms.IntegerField(widget=forms.HiddenInput(), required=False)
    klant_emailadres = forms.CharField(widget=forms.EmailField, required=False)
    class Meta:
        model = Klant
        fields = ('id', 'klant_voornaam', 'klant_achternaam', 'klant_telefoonnummer', 'klant_emailadres')


class ApparaatForm(forms.ModelForm):
    class Meta:
        model = Apparaat
        fields = (
            'apparaat_merk', 'apparaat_type',
            'apparaat_accessoires', 'apparaat_staat',
        )


class FactuurForm(forms.ModelForm):
    factuur_werkzaamheden = forms.CharField(widget=forms.Textarea, max_length=10000) 
    class Meta:
        model = Factuur
        fields = (
            'factuur_werkzaamheden', 'factuur_artikelen',
        )


class ArtikelForm(forms.ModelForm):
    nieuw_artikel_omschrijving = forms.CharField(widget=forms.Textarea, max_length=200)
    class Meta:
        model = NieuwArtikel
        fields = (
            'nieuw_artikel_naam', 'nieuw_artikel_prijs', 'nieuw_artikel_omschrijving'
        )


class UserRegistratie(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)
    username = forms.CharField(help_text="Alleen letters, nummers en @/./+/-/_ toegestaan.")

    class Meta:
        model = User
        fields = ('username', 'email', 'password')


class UserLogin(forms.Form):
    gebruikersnaam = forms.CharField(max_length=100)
    wachtwoord =  forms.CharField(widget=forms.PasswordInput)


class KlantZoek(forms.Form):
    klantnummer = forms.IntegerField()


class OpmerkingenForm(forms.Form):

    OPMERKING_TYPE_CHOICES = (
        ('informatie', 'informatie'),
        ('vraag', 'vraag'),
    )
    opmerkingen = forms.CharField(widget=forms.Textarea, max_length=500)
    opmerking_type = forms.ChoiceField(choices=OPMERKING_TYPE_CHOICES)
    user_list = forms.ChoiceField(choices=[(u.id, u.username) for u in User.objects.all()])

    def clean_opmerkingen(self):
        opmerkingen = self.cleaned_data.get('opmerkingen')
        if 'something' not in opmerkingen:
            raise forms.ValidationError('Something must be in opmerkingen field.')
        return opmerkingen


class TicketSearchForm(forms.Form):
    apparaat_merk = forms.CharField(max_length=50, required=False) 
    ticket_onderwerp = forms.CharField(max_length=50, required=False)
    ticket_body = forms.CharField(max_length=50, required=False)
    klant_achternaam = forms.CharField(max_length=50, required=False)


class KlantSearchForm(forms.Form):
    klant_voornaam = forms.CharField(max_length=50, required=False)
    klant_achternaam = forms.CharField(max_length=50, required=False)
    klant_postcode = forms.CharField(max_length=6, required=False, disabled=True, widget=forms.TextInput(attrs={'placeholder': 'Coming soon..'}))
    klant_woonplaats = forms.CharField(max_length=50, required=False, disabled=True, widget=forms.TextInput(attrs={'placeholder': 'Coming soon..'}))


class AntwoordForm(forms.Form):
    antwoord_body = forms.CharField(max_length=500, widget=forms.Textarea)


class ArtikelBoolean(forms.Form):
    nieuw_artikel = forms.BooleanField(required=False)

backend/tickets/templates/tickets/apparaat_form.html
{% extends "base.html" %}

{% block body %}

{% load staticfiles %}

{% if perms.tickets.add_ticket %}
<div class="ticket-form-wrapper">

    <div class="registratie-info">
        <h2>Stap 2 van de 3</h2>
        <h3>Klant gegevens</h3>
        <p>Voornaam: {{ klant.klant_voornaam }}</p>
        <p>Achternaam: {{ klant.klant_achternaam }}</p>
        <p>Telefoonnummer: {{ klant.klant_telefoonnummer }}</p>
    </div>

    <div class="ticket-input block">
        <form class="ticket-form block" method="post">
            {% csrf_token %}
            <h3 class="full">Apparaat registratie</h3>
            {% if apparaten %}
            <div class="snel-zoek" class="site-naam show">
                
                <h3>Gekoppelde apparaten</h3>
                    {% for apparaat in apparaten %}

                    <li><a class="reply-btn-inv btn-medium" href="{% url 'tickets:klant_ticket' apparaat.pk %}">{{ apparaat.apparaat_merk }} {{ apparaat.apparaat_type }}</a></li>

                    {% endfor %}
            </div>
            {% endif %}
            

            {{ apparaat_form }}
            <br>
            <input onclick="window.history.back()" class="primary-btn-inv btn-large" type="button" value="Vorige"/>
            <input class="primary-btn btn-large" type='submit' value="Volgende" />
        </form>



    </div>
</div>


{% else %}

<p>U heeft niet de juiste bevoegdheden om een ticket aan te maken :(</p>

{% endif %}

{% endblock %}

backend/tickets/templates/tickets/apparaat_update_form.html
{% extends "base.html" %}

{% block body %}

{% load staticfiles %}

{% if perms.tickets.change_apparaat %}
<div class="ticket-form-wrapper">

    <div class="ticket-input block">
        <form class="ticket-form block" method="post">
            {% csrf_token %}
            <h3 class="full">Apparaat registratie <span id="id_klant_gegevens"></span></h3>

            <p>
                <label for="{{ form.apparaat_merk.id_for_label }}">Merk:</label>
                {{ form.apparaat_merk }}
            </p>
            <p>
                <label for="{{ form.apparaat_type.id_for_label }}">Type:</label>
                {{ form.apparaat_type }}
            </p>
            <p>
                <label for="{{ form.apparaat_accessoires.id_for_label }}">Accessoires:</label>
                {{ form.apparaat_accessoires }}
            </p>
            <p>
                <label for="{{ form.apparaat_staat.id_for_label }}">Staat:</label>
                {{ form.apparaat_staat }}
            </p>

            <input class="full primary-btn btn-medium" type='submit' value="Aanpassen" />
            <a href="{% url 'tickets:delete_apparaat' object.id %}" class="danger-btn btn-medium link-btn">Verwijderen</a>
            <input onclick="window.history.back()" class="primary-btn-inv btn-medium" type="button" value="Vorige"/>
        </form>



    </div>
</div>


{% else %}

<p>U heeft niet de juiste bevoegdheden om een ticket aan te maken :(</p>

{% endif %}

{% endblock %}

backend/tickets/templates/tickets/base.html
{% load static %}
<!DOCTYPE html>
<html lang="nl">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link rel="stylesheet" href="{% static 'tickets/css/style.css' %}">
  <link rel="stylesheet" href="{% static 'tickets/css/font-awesome.css' %}">
  {% if title %}
  <title>{{ title }}</title>
  {% else %}
  <title>IctFabriek</title>
  {% endif %}
  <meta name="theme-color" content="#009688">
</head>
<body>
    <div class="navbar">
        <div class="merk-logo">
            <a href="{% url 'tickets:index' %}"><img class="normal-img" id="site-logo" src="{% static 'tickets/img/dif_logo wit_klein.png' %}"></a>
        </div>
        <div id="nav-elements" class="nav-elements show">
            <ul>
                <li><a {% if title == "Home" %}class="active"{% endif %} href="{% url 'tickets:index' %}">Home</a></li>
                <li><a {% if title == "Nieuw Ticket" %}class="active"{% endif %} href="{% url 'tickets:nieuw_klant' %}">Nieuw Ticket</a></li>
                <li class="dropdown"><a {% if title == "Overzicht" %}class="active"{% endif %} href="javascript:void(0)" class="dropbtn">Overzicht</a>
                    <div class="dropdown-content">
                        <a href="{% url 'tickets:overzicht_ticket_open' %}">Openstaande tickets</a>
                        <a href="{% url 'tickets:overzicht_klant' %}">Alle klanten</a>
                        <a href="{% url 'tickets:overzicht_ticket' %}">Alle tickets</a>
                    </div>
                </li>
                {% if user.is_staff %}
                <li><a {% if title == "Admin" %}class="active"{% endif %} href="{% url 'admin:index' %}">Admin</a></li>
                {% endif %}
                <li class="dropdown"><a href="#"><i class="fa fa-bell-o">({{ notifications|length }})</i></a>
                    <div class="dropdown-content">
                    {% if notifications %}
                        {% for notification in notifications %}
                            <div class="notificatie-body">
                                <a onclick="markeerAlsGelezen('{{ notification.id }}')" {% if notification.notificatie_opmerking %} href="{% url 'tickets:detail' notification.notificatie_opmerking.opmerking_ticket.id %}" {% else %} href="{% url 'tickets:detail' notification.notificatie_antwoord.antwoord_opmerking.opmerking_ticket.id %}" {% endif %} >{{ notification.notificatie_body }}</a>
                                <a href="{% url 'tickets:delete_notificatie' notification.id %}" class="close-btn">&times;</a> 
                            </div>
                        {% endfor %}
                    {% else %}
                        <div class="notificatie-body">
                            <a href="#">Er zijn geen ongelezen notificaties.</a>
                        </div>
                    {% endif %}
                        <div style="background-color:#009688;" class="notificatie_body">
                            <a style="font-weight:600; padding:5px 1em; color:white;" href="{% url 'tickets:overzicht_notificatie' %}">Alle notificaties</a>
                        </div>
                    </div>
                </li>
                {% if user.is_authenticated %}
                <li><a href="{% url 'tickets:loguit' %}">Loguit</a> | {{ user.username|capfirst }} </li>
                {% else %}
                <li><a href="{% url 'tickets:login' %}">Login</a></li>
                {% endif %}
            </ul>
        </div>
        <div class="nav-toggle">
            <div id="hide-nav">
                <p>&and;</p>
            </div>
            <div id="show-nav">
                <p>&or;</p>
            </div>
        </div>
        
        <script>
            function markeerAlsGelezen(notificatie_id) {
                var xhr = new XMLHttpRequest();
                xhr.open("POST", "/tickets/ajax/notificatie_gezien/" + notificatie_id + "/");
                xhr.setRequestHeader('X-CSRFToken', '{{ csrf_token }}');
                xhr.send()
            }
        </script>
        
        <script>
            const hideNav = document.getElementById('hide-nav');
            const showNav = document.getElementById('show-nav');
            const navElem = document.getElementById('nav-elements');

            hideNav.addEventListener('click', function(){
                navElem.style.display = 'none';
                hideNav.style.display = 'none';
                showNav.style.display = 'block';
            })

            showNav.addEventListener('click', function(){
                navElem.style.display = 'block';
                hideNav.style.display = 'block';
                showNav.style.display = 'none';
            })
        </script>
    </div>

  <div class="container">

    <div class="wrapper">
     {% block body %}{% endblock %}
    </div>

    <footer>
        <p>&copy; Hans Beijk V1.1.4</p>
    </footer>

  </div>

  {% if messages %}
    <ul id="id_messages" class="messages slide-in">
        {% for message in messages %}
        {% if message.tags == 'info' %}
        <div class="modal" id="simpleModal">
            <div class="modal-content">
                <div class="modal-header">
                    <h2>Afhaalbewijs printen</h2>
                </div>
                <div class="modal-body">
                    <p>Ticket succesvol aangemaakt! Druk op onderstaande knop om een afhaalbewijs te printen.</p>
                </div>
                <div class="modal-footer">
                    <a href="{{ message }}" class="primary-btn-invert btn-medium" target="_new">Maak pdf</a>
                    <a href="javascript:void(0);" onclick="document.getElementById('simpleModal').style.display = 'none';" id="sluit-btn" class="danger-btn btn-medium" type="button">Sluiten</a>
                </div>
            </div>
        </div>
        {% else %}
        <li class="{{ message.tags }}">{{ message }}</li>
        <script>
            const messages = document.getElementById('id_messages');
            setTimeout(function() {
                messages.classList.remove('slide-in');
                messages.classList.add('slide-out');
            }, 5000);
        </script>
        {% endif %}
        {% endfor %}
    </ul>

  {% endif %}

  
  
</body>

</html>

backend/tickets/templates/tickets/klant_update_form.html
{% extends "base.html" %}

{% block body %}

{% load staticfiles %}

{% if perms.tickets.change_klant %}
<div class="ticket-form-wrapper">

    <div class="ticket-input block">
        <form class="ticket-form block" method="post">
            {% csrf_token %}
            <h3 class="full">Klant registratie <span id="id_klant_gegevens"></span></h3>

            <p>
                <label for="{{ form.klant_voornaam.id_for_label }}">Voornaam:</label>
                {{ form.klant_voornaam }}
            </p>
            <p>
                <label for="{{ form.klant_achternaam.id_for_label }}">Achternaam:</label>
                {{ form.klant_achternaam }}
            </p>
            <p>
                <label for="{{ form.klant_telefoonnummer.id_for_label }}">Telefoonnummer:</label>
                {{ form.klant_telefoonnummer }}
            </p>

            <input class="full primary-btn btn-medium" type='submit' value="Aanpassen" />
            <a href="{% url 'tickets:delete_klant' object.id %}" class="danger-btn btn-medium link-btn">Verwijderen</a>
            <input onclick="window.history.back()" class="primary-btn-inv btn-medium" type="button" value="Vorige"/>
        </form>



    </div>
</div>


{% else %}

<p>U heeft niet de juiste bevoegdheden om een ticket aan te maken :(</p>

{% endif %}

{% endblock %}

backend/tickets/templates/tickets/login.html
{% extends "base.html" %}

{% block body %}
<div class="login-form">
    <form action="{% url 'tickets:login' %}" method="post">
        {% csrf_token %}

        {{ form }}

        <input type='submit' value="Login" />
    </form>
</div>
{% endblock %}